language: python
sudo: required
dist: trusty
python:
  - "2.7"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  # - "pypy"
# command to install dependencies
before_install:
  - sudo apt-get update -qq
  - make deps
  - make directories
install:
  - make travis-deps
  - make install
# command to run tests
script:
 - make tests
#publish results on coveralls
after_success:
 - coveralls
